### PR TITLE
Fixes Uri parsing issue (#350)

### LINKED ISSUE #350: Can't share music and video files
## Description
Error occurs on sharing video and audio files.

### Steps to reproduce
1. long press any video/audio file 
2. select share option
3. Wait for the file to download
4. Select any sharing app.
5. See the  error

### Updates 
After further testing, I found that the problem is with **Welcome to Amahi** server's video/audio files only.
Sharing feature is working fine with my remote and Local server.

@octacode please give some suggestions on this.

### PR DESCRIPTION
**Pull request by ArihantJain456**
fixes #350.

### CODE REVIEW

File: src/main/java/org/amahi/anywhere/util/Downloader.java [hunk 1]
```diff
@@ -115,12 +117,15 @@ private void finishDownloading() {
             String downloadUri = downloadInformation.getString(
                 downloadInformation.getColumnIndex(DownloadManager.COLUMN_LOCAL_URI));
 
-            if (downloadUri.substring(0, 7).matches("file://")) {
-                downloadUri = downloadUri.substring(7);
+            try {
+                URI uri = new URI(downloadUri);
+                downloadUri = uri.getPath();
+            } catch (URISyntaxException e) {
+                e.printStackTrace();
```
Comment (cpg) [inline src/main/java/org/amahi/anywhere/util/Downloader.java]: minor niggle. wouldn't we want to print the URI, tho, not the stack trace?

Comment (ArihantJain456) [reply src/main/java/org/amahi/anywhere/util/Downloader.java]: Stack trace contains the URI, but I too feel that printing URI only will work fine plus there is one more change that I think is necessary (`/file:` need to be removed from the Uri), so I will update the PR.
